
# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

mkdocs:
  configuration: website/mkdocs.yml

# Optionally declare the Python requirements required to build your docs
python:
   install:
   - requirements: website/requirements.txt
