# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  commands:
     - python -m pip install --exists-action=w --no-cache-dir -r website/requirements.txt
     - python -m mkdocs build --clean --site-dir $READTHEDOCS_OUTPUT/html --config-file website/mkdocs.yml
