language: python
cache: pip

matrix:
  include:
    - os: linux
      dist: xenial
      language: python
      python: "3.9"

    - os: linux
      dist: bionic
      language: python
      python: "3.7"
    - os: linux
      dist: bionic
      language: python
      python: "3.10"

    - os: linux
      dist: focal
      language: python
      python: "3.8"
    - os: linux
      dist: focal
      language: python
      python: "3.9"
    - os: linux
      dist: focal
      language: python
      python: "3.10"

install:
  # TODO: `setuptools` is pinned for the Python 3.7 builder and can be unpinned when removed.
  - "python -m pip install --upgrade pip build wheel virtualenv setuptools==62.3.4"
  # Make sure we get latest binary packages of OpenCV.
  # TODO: Add a Python 3.11 builder once newer versions of the `av` package are supported.
  # TODO: `opencv-python-headless` is pinned for the xenial build. Unpin `opencv-python-headless`
  # when https://github.com/opencv/opencv/issues/23090 is resolved.
  - "python -m pip install opencv-python-headless==4.6.0.66 opencv-contrib-python-headless==4.6.0.66 --only-binary :all:"
  # Install required packages.
  - "python -m pip install -r requirements_headless.txt"
  - "python -m build"

script:
  - "PACKAGE_VERSION=`python -c \"import dvr_scan; print(dvr_scan.__version__[1:].replace('-', '.'))\"`"

  # Unit Tests
  - python -m pytest tests/

  # Test CLI using source code
  - python -m dvr_scan -v
  - python -m dvr_scan -i tests/resources/simple_movement.mp4 -so -df 4 -et 100

  # Test CLI using source distribution
  - python -m pip install dist/dvr-scan-$PACKAGE_VERSION.tar.gz
  - dvr-scan -v
  - dvr-scan -i tests/resources/simple_movement.mp4 -so -df 4 -et 100
  # Cleanup
  - python -m pip uninstall -y dvr-scan

  # Test CLI using binary wheel
  - python -m pip install dist/dvr_scan-$PACKAGE_VERSION-py3-none-any.whl
  - dvr-scan -v
  - dvr-scan -i tests/resources/simple_movement.mp4 -so -df 4 -et 100
  # Cleanup
  - python -m pip uninstall -y dvr-scan
