language: python
cache: pip

matrix:
  include:
    - os: linux
      dist: xenial
      language: python
      python: "3.8"

    - os: linux
      dist: bionic
      language: python
      python: "3.9"

    - os: linux
      dist: bionic
      language: python
      python: "3.7"
    - os: linux
      dist: focal
      language: python
      python: "3.8"
    - os: linux
      dist: focal
      language: python
      python: "3.9"
    - os: linux
      dist: focal
      language: python
      python: "3.10"

install:
  - "python -m pip install --upgrade pip build wheel virtualenv"
  # Make sure we get latest binary packages of OpenCV.
  - "python -m pip install opencv-python-headless opencv-contrib-python-headless --only-binary :all:"
  # Install required packages.
  - "python -m pip install -r requirements_headless.txt"
  - "python -m build"

script:
  - python -m pytest tests/
  # Test CLI using source code
  - python -m dvr_scan -v
  - python -m dvr_scan -i tests/resources/simple_movement.mp4 -so -df 4 -et 100

  # Test CLI using source distribution
  - python -m pip install dist/dvr-scan-`python -c "import dvr_scan; print(dvr_scan.__version__[1:])"`.tar.gz
  - dvr-scan -v
  - dvr-scan -i tests/resources/simple_movement.mp4 -so -df 4 -et 100
  # Cleanup
  - python -m pip uninstall -y dvr-scan

  # Test CLI using binary wheel
  - python -m pip install dist/dvr_scan-`python -c "import dvr_scan; print(dvr_scan.__version__[1:])"`-py3-none-any.whl
  - dvr-scan -v
  - dvr-scan -i tests/resources/simple_movement.mp4 -so -df 4 -et 100
  # Cleanup
  - python -m pip uninstall -y dvr-scan
