# Build signed releases for DVR-Scan Windows x64

build: false

branches:
  only:
    - main
    - /releases\/.+/
    - /v.+-release/

skip_tags: false
skip_non_tags: true


environment:
  matrix:
    - PYTHON: "C:\\Python39-x64"

install:
  - echo TODO
