site_name: DVR-Scan
site_description: "Website and documentation for DVR-Scan, a program to automatically detect and save motion events in videos (e.g. security camera footage)."
site_author: "Brandon Castellano"

repo_url: https://github.com/Breakthrough/DVR-Scan
repo_name: "DVR-Scan on Github"
copyright: 'Copyright &copy; 2016-2022 Brandon Castellano.  All rights reserved.<br />Licensed under BSD 2-Clause (see the <a href="https://github.com/Breakthrough/DVR-Scan/blob/master/LICENSE" alt="link to latest LICENSE file on Github">LICENSE file</a> for details).'

#theme: mkdocs
theme: readthedocs
#google_analytics: ['UA-########-1', 'auto']

pages:
- 'DVR-Scan':
    - 'Introduction': 'index.md'
    - 'Download': 'download.md'
    - 'Changelog': 'changelog.md'
    - 'Contributing & Bug Reports': 'contributing.md'
    - 'License & Copyright Info': 'copyright.md'
- 'User Guide':
    - 'Quickstart': 'guide/quickstart.md'
    - 'Options': 'guide/options.md'
    - 'Config File': 'guide/config_file.md'
    - 'FAQ': 'guide/faq.md'
- 'External Resources':
    - 'Similar/Related Software': 'other/similar_software.md'
#    - 'Technical Resources & Articles': 'other/resources.md'

markdown_extensions: [fenced_code]
