# Build Portable Windows EXE (x64) Distribution for DVR-Scan

name: Windows Distribution

on:
  pull_request:
    paths:
      - dist/**
      - dvr_scan/**
      - tests/**
  push:
    paths:
      - dist/**
      - dvr_scan/**
      - tests/**
    tags:
      - v*-release
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip build wheel virtualenv setuptools
          pip install -r dist/requirements_windows.txt

      - name: Unit Test
        run: |
          python -m pytest tests/
