# Use YAPF to check DVR-Scan formatting (run `yapf -i -r dvr_scan tests` locally to fix)
name: Check Code Format

on:
  pull_request:
    paths:
      - .style.yapf
      - dvr_scan/**
      - tests/**
  push:
    paths:
      - .style.yapf
      - dvr_scan/**
      - tests/**

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Install yapf
        run: python -m pip install --upgrade yapf toml
      - name: Install DVR-Scan Dependencies
        run: python -m pip install -r requirements_headless.txt

      - name: Check Code Format (dvr_scan)
        run: python -m yapf --diff --recursive dvr_scan/
      - name: Check Code Format (tests)
        run: python -m yapf --diff --recursive tests/
